baseURL = 'https://kern.services/'
defaultContentLanguage = 'de'
title = 'kern.services'

[languages]
  [languages.de]
    languageName = 'DE'
    contentDir = 'content'
    weight = 1
  [languages.en]
    languageName = 'EN'
    contentDir = 'content'
    weight = 2

[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "node_modules"
    target = "assets/node_modules"
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[security]
  [security.funcs]
    getenv = ['^HUGO_', '^CF_']

[outputFormats]
  [outputFormats.HTML]
    mediaType = "text/html"
    isHTML = true
    permalinkable = true

[build]
  writeStats = true
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'

# Insights specific configurations
[permalinks]
  insights = "/insights/:year/:month/:title/"

[taxonomies]
  tag = "tags"
  category = "categories"
